@url = https://glowing-yodel-r47jqr6rqqq5fp49x-3000.app.github.dev/api/tarefas

GET {{url}}

###
POST {{url}}
Content-Type: application/json

{
    "id" : 10,
    "title" : "Executar Aplicação"
}

###
GET {{url}}/1